<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang='en'>
<head>
<title>Sequel::Error</title>
<meta name='viewport' content='width=device-width, initial-scale=1'>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
<link href='../../css/style.css' media='screen' rel='stylesheet' type='text/css'>
<script type='text/javascript'>
  function popupCode(url) {
    window.open(url, "Code", "resizable=yes,scrollbars=yes,toolbar=no,status=no,height=150,width=400")
  }
  
  function toggleCode(id) {
    var code = document.getElementById(id)
  
    code.style.display = code.style.display != 'block' ? 'block' : 'none'
    return true
  }
  
  // Make codeblocks hidden by default
  document.writeln('<' + 'style type="text/css">.method .source pre { display: none }<\/style>')
</script>
</head>
<body class='page'>
<div class='class' id='wrapper'>
<div class='header'>
<h1 class='name'><span class='type'>class</span>
Sequel::Error
</h1>
<ol class='paths'>
<li>
<a href="../../files/lib/sequel/exceptions_rb.html">lib/sequel/exceptions.rb</a>
</li>
</ol>
<div class='parent'>
Superclass:
<strong>StandardError</strong>
</div>
</div>
<div id='content'>
<div id='text'>
<div id='description'>
<p>The default exception class for exceptions raised by <a href="../Sequel.html"><code>Sequel</code></a>. All exception classes defined by <a href="../Sequel.html"><code>Sequel</code></a> are descendants of this class.</p>
</div>
<div id='method-list'>
<h2>Methods</h2>
<h3>Public Instance</h3>
<ol>
<li><a href="#method-i-cause">cause</a></li>
<li><a href="#attribute-i-wrapped_exception">wrapped_exception</a></li>
</ol>
</div>
<div id='context'>
</div>
<div id='section'>
<div id='attribute-list'>
<h2 class='section-bar'>Attributes</h2>
<div class='name-list'>
<table>
<tr class='top-aligned-row context-row'>
<td class='context-item-name'>
<a name='attribute-i-wrapped_exception'>wrapped_exception</a>
</td>
<td class='context-item-value'>[RW]</td>
<td class='context-item-desc'>
<p>If this exception wraps an underlying exception, the underlying exception is held here.</p>
</td>
</tr>
</table>
</div>
</div>
<div id='methods'>
<h2>Public Instance methods</h2>
<div class='method public-instance' id='method-method-i-cause'>
<a name='method-i-cause'></a>
<div class='synopsis'>
<span class='name'>cause</span><span class='arguments'>()</span>

</div>
<div class='description'>

<p>:nocov:  Returned the wrapped exception if one exists, otherwise use rubyâ€™s default behavior.</p>

</div>
<div class='source'>
<a class='source-toggle' href='#' onclick='toggleCode(&#39;method-i-cause-source&#39;); return false'>
[show source]
</a>
<pre id='method-i-cause-source'>   <span class="ruby-comment"># File lib/sequel/exceptions.rb</span>
<span class="line-num">16</span> <span class="ruby-keyword">def</span> <span class="ruby-identifier ruby-title">cause</span>
<span class="line-num">17</span>   <span class="ruby-identifier">wrapped_exception</span> <span class="ruby-operator">||</span> <span class="ruby-keyword">super</span>
<span class="line-num">18</span> <span class="ruby-keyword">end</span></pre>
</div>
</div>
</div>
</div>

</div>
</div>

<div id='footer-push'></div>
</div>
<div id='footer'>
<a href="https://github.com/jeremyevans/hanna"><strong>Hanna</strong> RDoc template</a>
</div>
</body>
</html>
